title: CS/BBA University Work
description: A hopefully legal archive of study material and practice work

theme: jekyll-theme-cayman
kramdown:
  parse_block_html: true
exclude:
  - PMATH348/PMATH348_Lecture_Notes*
  - CO250/notes-obsidian*
plugins:
  - jemoji
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
